# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a97d8f59cd8d4525dba646f397ef73160ae6899dc6cf31392f633c48a2324961ee407c0cdc88ae661f115e34cd68b496843a4b6f8988e59c0b43eff42a1d804

test:
  secret_key_base: 0edcc1d5fc9c669085bbd35d6212391296c80c0a157ff7317cb76a68be1c2a6d6e5366c310fdb3e00f4b0ad3e78ca241c623db0b71edd051cd61cfbef6e49258

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
